version: "3.3"

services:
    mongo: 
        image: mongo
        ports:
            - 27017:27017

    express:
        image: mongo-express
        ports:
            - 8081:8081
        depends_on: 
            - mongo
    back:
        build: spring-auth-demo
        ports:
            - 8080:8080
        environment: 
            - SERVER_PORT=8080
            - MONGO_HOST=mongo
        depends_on: 
            - mongo
    
    front:
        build: auth-angular-banque
        ports:
            - 80:80